// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClwl2gnpFMPS2jkYOS0eqQPG9DIvwKIhc',
    appId: '1:571483345015:web:623f2f793a30e34f0ff672',
    messagingSenderId: '571483345015',
    projectId: 'apartment-rental-free-p-7i4tzz',
    authDomain: 'apartment-rental-free-p-7i4tzz.firebaseapp.com',
    databaseURL: 'https://apartment-rental-free-p-7i4tzz-default-rtdb.firebaseio.com',
    storageBucket: 'apartment-rental-free-p-7i4tzz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHwGRVCtwL1zvZ9Tqj9RhOY3kfE_WtM-M',
    appId: '1:571483345015:android:3e384e489dc039410ff672',
    messagingSenderId: '571483345015',
    projectId: 'apartment-rental-free-p-7i4tzz',
    databaseURL: 'https://apartment-rental-free-p-7i4tzz-default-rtdb.firebaseio.com',
    storageBucket: 'apartment-rental-free-p-7i4tzz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRrNB5UNu-fcg70Lo3VPNpJpCChi_oxaM',
    appId: '1:571483345015:ios:2b6de476e1eb801d0ff672',
    messagingSenderId: '571483345015',
    projectId: 'apartment-rental-free-p-7i4tzz',
    databaseURL: 'https://apartment-rental-free-p-7i4tzz-default-rtdb.firebaseio.com',
    storageBucket: 'apartment-rental-free-p-7i4tzz.firebasestorage.app',
    iosBundleId: 'com.example.locationMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRrNB5UNu-fcg70Lo3VPNpJpCChi_oxaM',
    appId: '1:571483345015:ios:2b6de476e1eb801d0ff672',
    messagingSenderId: '571483345015',
    projectId: 'apartment-rental-free-p-7i4tzz',
    databaseURL: 'https://apartment-rental-free-p-7i4tzz-default-rtdb.firebaseio.com',
    storageBucket: 'apartment-rental-free-p-7i4tzz.firebasestorage.app',
    iosBundleId: 'com.example.locationMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClwl2gnpFMPS2jkYOS0eqQPG9DIvwKIhc',
    appId: '1:571483345015:web:e33603ca7d3f4a370ff672',
    messagingSenderId: '571483345015',
    projectId: 'apartment-rental-free-p-7i4tzz',
    authDomain: 'apartment-rental-free-p-7i4tzz.firebaseapp.com',
    databaseURL: 'https://apartment-rental-free-p-7i4tzz-default-rtdb.firebaseio.com',
    storageBucket: 'apartment-rental-free-p-7i4tzz.firebasestorage.app',
  );
}
